import { useState } from 'react';
import { z } from 'zod';
import { Modal } from '../../components/ui';
import type { Booking } from '../../types';

export function EditBookingModal({ booking, onSave, onClose }: { booking: Booking; onSave: (data: { leadPax: string; amount: number; travelDate: string }) => Promise<void>; onClose: () => void }) {
  const [leadPax, setLead] = useState(booking.leadPax); const [amount, setAmount] = useState(booking.amount); const [travelDate, setDate] = useState(booking.travelDate.slice(0, 10)); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async () => { const result = z.object({ leadPax: z.string().min(2), amount: z.number().positive(), travelDate: z.string().min(8) }).safeParse({ leadPax, amount, travelDate }); if (!result.success) { setError('Enter a valid passenger, date, and positive amount.'); return; } setBusy(true); try { await onSave({ ...result.data, travelDate: new Date(result.data.travelDate).toISOString() }); } finally { setBusy(false); } };
  return <Modal title={`Edit booking ${booking.bookingId}`} onClose={onClose}><div className="form-grid"><label>Lead passenger<input value={leadPax} onChange={event => setLead(event.target.value)} /></label><label>Travel date<input type="date" value={travelDate} onChange={event => setDate(event.target.value)} /></label><label>Amount<input type="number" min="1" value={amount} onChange={event => setAmount(Number(event.target.value))} /></label>{error && <p className="form-error">{error}</p>}</div><div className="modal-actions"><button className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy} onClick={() => void submit()}>{busy ? 'Saving…' : 'Save changes'}</button></div></Modal>;
}

export function PaymentModal({ booking, paymentModes, accounts, onSave, onClose }: { booking: Booking; paymentModes: string[]; accounts: string[]; onSave: (data: { amount: number; paymentMode: string; account: string }) => Promise<void>; onClose: () => void }) {
  const [amount, setAmount] = useState(0); const [mode, setMode] = useState(paymentModes[0] ?? 'Bank transfer'); const [account, setAccount] = useState(accounts[0] ?? 'HDFC Current'); const [busy, setBusy] = useState(false);
  return <Modal title={`Record payment · ${booking.bookingId}`} onClose={onClose}><div className="form-grid"><label>Amount<input type="number" min="1" value={amount || ''} onChange={event => setAmount(Number(event.target.value))} /></label><label>Payment mode<select value={mode} onChange={event => setMode(event.target.value)}>{paymentModes.map(value => <option key={value}>{value}</option>)}</select></label><label>Account<select value={account} onChange={event => setAccount(event.target.value)}>{accounts.map(value => <option key={value}>{value}</option>)}</select></label></div><div className="modal-actions"><button className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={amount <= 0 || busy} onClick={async () => { setBusy(true); try { await onSave({ amount, paymentMode: mode, account }); } finally { setBusy(false); } }}>{busy ? 'Recording…' : 'Record payment'}</button></div></Modal>;
}
