import { ArrowLeft, Download, Edit3, Eye, FileText, RefreshCcw, Share2, WalletCards } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { z } from 'zod';
import { useAppSelector } from '../../app/hooks';
import { Breadcrumbs } from '../../components/AppShell';
import { ActionMenu, Modal, Pagination, Toast } from '../../components/ui';
import { localErrorMessage, localRepository } from '../../data/localRepository';
import type { Customer, LedgerEntry, Meta } from '../../types';
import { financialYearRange, money } from '../../utils/finance';

const fy=financialYearRange();
const csvCell=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;

export function LedgerPage(){
  const {customerId,bookingId}=useParams();const[searchParams]=useSearchParams();const navigate=useNavigate();const options=useAppSelector(state=>state.bookings.options);
  const[customer,setCustomer]=useState<Customer|null>(null);const[entries,setEntries]=useState<LedgerEntry[]>([]);const[meta,setMeta]=useState<Meta>({page:1,limit:10,total:0,totalPages:1});const[summary,setSummary]=useState({balance:0,label:'You Collect',currency:'INR'});
  const[filters,setFilters]=useState({from:searchParams.get('from')??fy.from,to:searchParams.get('to')??fy.to,pendingOnly:searchParams.get('pendingOnly')==='true',page:1,limit:10});
  const[modal,setModal]=useState<'payment-gave'|'payment-got'|'pdf'|'download'|'share'|null>(null);const[selectedEntry,setSelectedEntry]=useState<LedgerEntry|null>(null);const[toast,setToast]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const resolveCustomerId=useCallback(async()=>{if(customerId)return customerId;if(!bookingId)throw new Error('A customer or booking ID is required.');return localRepository.resolveCustomerForBooking(bookingId);},[bookingId,customerId]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{await Promise.resolve();const id=await resolveCustomerId();const ledger=localRepository.ledger(id,filters);setCustomer(ledger.customer);setEntries(ledger.entries);setMeta(ledger.meta);setSummary(localRepository.ledgerSummary(id));}catch(loadError){setError(localErrorMessage(loadError,'Could not load the customer ledger'));}finally{setLoading(false);}},[filters,resolveCustomerId]);
  useEffect(()=>{void load();},[load]);
  const downloadCsv=async()=>{try{const id=await resolveCustomerId();const allEntries=localRepository.exportLedger(id,{from:filters.from,to:filters.to,pendingOnly:filters.pendingOnly});const rows=[['ID','Service','Date','Status','Account','Amount','Closing Balance'],...allEntries.map(entry=>[entry.entryId,entry.serviceType,entry.transactionDate,entry.status,entry.account,entry.signedAmount,entry.closingBalance])];const blob=new Blob([rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv'});const anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=`${customer?.name??'customer'}-ledger.csv`;anchor.click();URL.revokeObjectURL(anchor.href);setToast('Ledger downloaded');setModal(null);}catch(downloadError){setToast(localErrorMessage(downloadError,'Could not download ledger'));}};
  const downloadReceipt=(entry:LedgerEntry)=>{const blob=new Blob([`Receipt ${entry.entryId}\nDate: ${entry.transactionDate}\nAmount: ${entry.amount}\nMode: ${entry.paymentMode}\nAccount: ${entry.account}`],{type:'text/plain'});const anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=`${entry.entryId}-receipt.txt`;anchor.click();URL.revokeObjectURL(anchor.href);setToast('Receipt downloaded');};
  if(loading&&!customer)return <div className="page-loader">Loading customer ledger…</div>;
  if(error&&!customer)return <div className="inline-error">{error}<button onClick={()=>void load()}>Retry</button></div>;
  if(!customer)return null;
  return <><Breadcrumbs items={['Home','Finance','Customers','Ledger']}/><div className="ledger-heading"><div><button className="icon-btn" onClick={()=>navigate('/finance/bookings')} aria-label="Back"><ArrowLeft/></button><div><h1>Ledger <i/> {customer.name} <i/> {customer.customerId}</h1><p>{customer.email} · {customer.phone}</p></div></div><div><button className="icon-btn" aria-label="View customer"><Eye/></button><button className="icon-btn" aria-label="Edit customer"><Edit3/></button></div></div>
    <section className="ledger-balance"><span className={`balance-icon ${summary.balance<0?'red':'green'}`}><WalletCards/></span><div><span>{summary.label}</span><strong className={summary.balance<0?'red':'green'}>{money(summary.balance,summary.currency)}</strong><small>Current closing balance</small></div><button className="icon-btn" onClick={()=>void load()} aria-label="Refresh balance"><RefreshCcw/></button><div className="ledger-pay-actions"><button className="btn danger" onClick={()=>setModal('payment-gave')}>You Gave</button><button className="btn success" onClick={()=>setModal('payment-got')}>You Got</button></div></section>
    <section className="ledger-actions"><div className="split-button"><button className="btn primary" onClick={()=>setModal('pdf')}><FileText/>View PDF</button><ActionMenu items={[{label:'Download',icon:<Download/>,onClick:()=>setModal('download')},{label:'Share',icon:<Share2/>,onClick:()=>setModal('share')}]} label="Ledger document actions"/></div></section>
    <section className="ledger-filters"><label><span>Booking Date</span><input type="date" value={filters.from} onChange={event=>setFilters({...filters,from:event.target.value,page:1})}/><i>to</i><input type="date" value={filters.to} onChange={event=>setFilters({...filters,to:event.target.value,page:1})}/></label><label className="toggle"><input type="checkbox" checked={filters.pendingOnly} onChange={event=>setFilters({...filters,pendingOnly:event.target.checked,page:1})}/><span/>Pending invoices only</label><button className="btn text" onClick={()=>setFilters({...filters,from:fy.from,to:fy.to,pendingOnly:false,page:1})}>Reset filters</button></section>
    <section className="table-card">{error&&<div className="inline-error">{error}<button onClick={()=>void load()}>Retry</button></div>}<LedgerTable entries={entries} onView={setSelectedEntry} onReceipt={downloadReceipt}/><Pagination {...meta} noun="entries" onPage={page=>setFilters({...filters,page})} onLimit={limit=>setFilters({...filters,limit,page:1})}/></section>
    {modal?.startsWith('payment')&&<LedgerPaymentModal direction={modal==='payment-got'?'got':'gave'} customerId={customer.id} paymentModes={options.paymentModes} accounts={options.accounts} onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);setToast('Payment recorded');await load();}}/>}
    {modal==='pdf'&&<Modal title={`Ledger | ${customer.name} | ${customer.customerId}`} wide onClose={()=>setModal(null)}><div className="pdf-actions"><button className="btn secondary" onClick={()=>window.print()}><Download/>Print / Save PDF</button><button className="btn secondary" onClick={()=>setModal('share')}><Share2/>Share</button></div><div className="pdf-view"><LedgerTable entries={entries} onView={setSelectedEntry} onReceipt={downloadReceipt}/></div></Modal>}
    {modal==='download'&&<Modal title="Download ledger" onClose={()=>setModal(null)}><div className="form-grid"><label>File name<input defaultValue={`${customer.name} ledger`}/></label><label>Format<select><option>CSV</option></select></label><label>From<input type="date" value={filters.from} readOnly/></label><label>To<input type="date" value={filters.to} readOnly/></label></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setModal(null)}>Cancel</button><button className="btn primary" onClick={()=>void downloadCsv()}><Download/>Download</button></div></Modal>}
    {modal==='share'&&<ShareModal customerId={customer.id} onClose={()=>setModal(null)} onToast={setToast}/>} 
    {selectedEntry&&<Modal title={`Ledger entry ${selectedEntry.entryId}`} onClose={()=>setSelectedEntry(null)}><div className="form-grid"><label>Service<input value={selectedEntry.serviceType} readOnly/></label><label>Status<input value={selectedEntry.status} readOnly/></label><label>Amount<input value={money(selectedEntry.amount)} readOnly/></label><label>Account<input value={selectedEntry.account} readOnly/></label></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setSelectedEntry(null)}>Close</button><button className="btn primary" onClick={()=>downloadReceipt(selectedEntry)}><Download/>Download receipt</button></div></Modal>}
    {toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</>;
}

function LedgerTable({entries,onView,onReceipt}:{entries:LedgerEntry[];onView:(entry:LedgerEntry)=>void;onReceipt:(entry:LedgerEntry)=>void}){return <div className="table-scroll"><table className="data-table ledger-table"><thead><tr><th>ID</th><th>Service</th><th>Booking / Payment Date</th><th>Status / Mode</th><th>Account</th><th>Amount</th><th>Closing Balance</th><th>Actions</th></tr></thead><tbody>{entries.length===0?<tr><td colSpan={8}><div className="empty-state"><WalletCards/><h3>No ledger entries</h3><p>No entries match the selected date range.</p></div></td></tr>:entries.map(entry=><tr key={entry.id}><td><b>{entry.entryId}</b><small>{entry.bookingId}</small></td><td>{entry.serviceType}</td><td>{new Date(entry.transactionDate).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</td><td><span className="badge confirmed">{entry.status}</span><small>{entry.paymentMode}</small></td><td>{entry.account}</td><td><strong className={entry.signedAmount>=0?'green':'red'}>{entry.signedAmount>=0?'+':'−'}{money(entry.signedAmount)}</strong></td><td><strong className={entry.closingBalance<0?'red':'green'}>{money(entry.closingBalance)}</strong></td><td><ActionMenu items={[{label:'View details',onClick:()=>onView(entry)},{label:'Download receipt',onClick:()=>onReceipt(entry)}]}/></td></tr>)}</tbody></table></div>;}

function LedgerPaymentModal({direction,customerId,paymentModes,accounts,onClose,onSaved}:{direction:'gave'|'got';customerId:string;paymentModes:string[];accounts:string[];onClose:()=>void;onSaved:()=>Promise<void>}){const[amount,setAmount]=useState(0);const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[mode,setMode]=useState(paymentModes[0]??'Bank transfer');const[account,setAccount]=useState(accounts[0]??'HDFC Current');const[reference,setReference]=useState('');const[notes,setNotes]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{const data={direction,amount,transactionDate:date,paymentMode:mode,account,reference,notes};if(!z.object({amount:z.number().positive(),transactionDate:z.string().min(8),paymentMode:z.string().min(2),account:z.string().min(2)}).safeParse(data).success){setError('Enter a positive amount and all required details.');return;}setBusy(true);try{localRepository.recordCustomerPayment(customerId,data);await onSaved();}catch(saveError){setError(localErrorMessage(saveError,'Could not save payment'));}finally{setBusy(false);}};return <Modal title={direction==='got'?'Record money received':'Record money paid'} onClose={onClose}><div className="form-grid"><label>Amount<input type="number" value={amount||''} min="1" onChange={event=>setAmount(Number(event.target.value))}/></label><label>Date<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Mode<select value={mode} onChange={event=>setMode(event.target.value)}>{paymentModes.map(value=><option key={value}>{value}</option>)}</select></label><label>Account<select value={account} onChange={event=>setAccount(event.target.value)}>{accounts.map(value=><option key={value}>{value}</option>)}</select></label><label>Reference<input value={reference} onChange={event=>setReference(event.target.value)}/></label><label>Notes<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label>{error&&<p className="form-error">{error}</p>}</div><div className="modal-actions"><button className="btn secondary" onClick={onClose}>Cancel</button><button className={`btn ${direction==='got'?'success':'danger'}`} disabled={busy} onClick={()=>void submit()}>{busy?'Saving…':'Save payment'}</button></div></Modal>;}

function ShareModal({customerId,onClose,onToast}:{customerId:string;onClose:()=>void;onToast:(message:string)=>void}){const[pending,setPending]=useState(false);const[range,setRange]=useState(false);const[from,setFrom]=useState('');const[to,setTo]=useState('');const[error,setError]=useState('');const share=async(kind:'copy'|'whatsapp'|'email')=>{try{const url=`${location.origin}${localRepository.shareLedgerPath(customerId,{pending,range,from,to})}`;if(kind==='copy'){await navigator.clipboard?.writeText(url);onToast('Ledger link copied');}else if(kind==='whatsapp')window.open(`https://wa.me/?text=${encodeURIComponent(url)}`,'_blank','noopener');else location.href=`mailto:?subject=Customer ledger&body=${encodeURIComponent(url)}`;onClose();}catch(shareError){setError(localErrorMessage(shareError,'Could not create share link'));}};return <Modal title="Ledger Settings" onClose={onClose}><label className="setting-check"><input type="checkbox" checked={pending} onChange={event=>setPending(event.target.checked)}/><div><b>Share Pending Invoices only</b><span>Display only pending invoices that are not settled yet</span></div></label><label className="setting-check"><input type="checkbox" checked={range} onChange={event=>setRange(event.target.checked)}/><div><b>Share in a custom Date Range</b><span>Only data of selected date range would be shown</span></div></label>{range&&<div className="date-pair"><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/><span>to</span><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></div>}{!range&&<p className="share-note">Note: This link contains full ledger data</p>}{error&&<p className="form-error">{error}</p>}<div className="share-methods"><button className="btn success" onClick={()=>void share('whatsapp')}>Share on WhatsApp</button><button className="btn secondary" onClick={()=>void share('email')}>Share on Email</button><button className="btn primary" onClick={()=>void share('copy')}>Copy link</button></div></Modal>;}
